icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
critical_bg = "#171717"
good_bg = "#171717"
idle_bg = "#171717"
info_bg = "#171717"
separator_bg = "#171717"
warning_bg = "#171717"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "battery"
interval = 30
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %b %d %I:%M %p"
